### ISSUE TITLE
!please; isn't working in my setup

### ISSUE THREAD

**Issue by furzeface** [HashanP/postcss-spiffing#12]
Hi,

All rules are working other than `!please;` - which is the only one that I want!

---

I’ve tested it thoroughly and reduced it down to these code examples:
### `gulpfile.js`

``` js
gulp.task('styles', function () {
  return gulp.src('source/styles/main.scss')
    .pipe(sass())
    .pipe(postcss([
      spiffing()
    ]))
    .pipe(gulp.dest('./dist'))
})
```
### SCSS

``` scss
.frame {
  background-photograph: url("/queen.png") !please;
}
```
### Console error:

``` sh
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: source/styles/main.scss
Error: Invalid CSS after '...l("/queen.png")': expected expression (e.g. 1px, bold), was "!please;"
        on line 18 of source/styles/_trumps.iframe-embed.scss
>>   background-photograph: url("/queen.png") !please;
   ------------------------------------------^
```
### `package.json`

``` json
"gulp": "^3.9.0",
"gulp-postcss": "^6.1.1",
"postcss-spiffing": "^0.1.0",
```

Has anyone else had this particular issue? Any help would be appreciated. Thanks! :octocat:

**Comment by hashanp** [comment]
I do not think this is an issue with `postcss-spiffing` but with `sass`. Sass does not treat `!please` as proper syntax for `.scss` files. There are 2 solutions:
- Apply the `postcss` transformations before `sass`; the way to do this would be to use [postcss-scss](https://github.com/postcss/postcss-scss). This will not compile `scss` to `css`, but allow `postcss` transformations to be applied to `.scss` file. The output will still be a `.scss` file,  which can be then compiled to a `.css` file.
- Another solution might be to use `postcss` alternatives to Sass. I would particularly recommend [precss](https://github.com/jonathantneal/precss).

**Comment by furzeface** [comment]
Brilliant, thanks! 

I've been looking into alternatives for sass as I only lightly use it anyway. This will be my next step.

Thanks again :)
