### ISSUE TITLE
Update postcss version, tests and so on

### ISSUE THREAD

**Issue by igoradamenko** [HashanP/postcss-spiffing#9]
Hi!

I wanted to fix #2 and also noticed that plugin depends on old version of postcss and also I couldn't run tests without errors. Can I update all of that in one PR or I should to create several PRs?

**Comment by igoradamenko** [comment]
As I see test fails 'cause plugin depends on 4.x.x version of postcss, but `index.js` contains `css.walkDecls` from 5.x.x versions.

**Comment by hashanp** [comment]
You can update everything in one pull request. :smiley: And you're right, for some reason I updated the `devDependencies` property, but not the actual `dependencies` in `package.json` to `postcss@5.x.x`.

**Comment by igoradamenko** [comment]
Okay, thank you. I'll make a PR soon! :+1:

**Comment by igoradamenko** [comment]
PR is there: #10.
